services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '8181:5432'
  go-httpbin:
    ports:
      - '9000:8080'
    image: 'mccutchen/go-httpbin:latest'